spring.application.name=backend-clintec

# Base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Puerto
server.port=${SERVER_PORT}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Logging base
logging.file.name=logs/clintec.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%t] %logger{39} : %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

# Perfil activo cambias esto segun el ambiente
spring.profiles.active=dev