# Swagger deshabilitado
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Sin queries en consola
spring.jpa.show-sql=false

# Logging minimo
logging.level.root=WARN
logging.level.com.terreneitors.backendclintec=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.security=WARN

spring.output.ansi.enabled=NEVER
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%t] %logger{39} : %msg%n