# Base de datos
spring.datasource.url=jdbc:mysql://prod-db:3306/clintec_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# Puerto
server.port=8080

# JWT
jwt.secret=secret_super_seguro_produccion
jwt.expiration=86400000