spring.application.name=backend-clintec
# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/clintec_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Terres1009.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ? validate: verifica que el esquema existe, no lo recrea
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Puerto
server.port=8080

# JWT ? cambia este secret en producción
jwt.secret=losmejoresingenierosdelau2026por100preporquesi
jwt.expiration=86400000